language: c
before_install:
  - mkdir Exposer
  - mv !(Exposer|simavr)  Exposer
  - sudo apt-get install -y freeglut3 freeglut3-dev 
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid
--make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.10-linux64.tar.xz
  - tar xf arduino-1.6.10-linux64.tar.xz
  - sudo mv arduino-1.6.10 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - sudo apt-get install libelf-dev gcc-avr binutils-avr gdb-avr avr-libc avrdude
  - make -C ./simavr

script:
  - arduino --board arduino:avr:nano:cpu=atmega328 --pref build.path=$PWD/Exposer/build --verify $PWD/Exposer/Exposer.ino
  - sudo sh .travisScripts/start_simavr.sh
  - sudo python Exposer/python/exposer.py /tmp/simavr-uart0
  - sudo pkill -9 simduino.elf
